### ISSUE TITLE
RxRealm requires realm-cocoa in Cartfile

### ISSUE THREAD

**Issue by nateboxer** [schwa/punic#34]
I was trying to add "RxSwiftCommunity/RxRealm" to my project but Punic failed in the resolve stage with a stack trace. The way I worked around this was to run Carthage update to determine what might be missing. Carthage handled this just fine, but then I noticed it added "realm/realm-cocoa" to the Cartfile.resolved file. When I added the same to the Cartfile, Punic was able to resolve properly without stack tracing.

Here is the trace when I included RxRealm in my Cartfile and ran punic resolve:

Traceback (most recent call last):
  File "/usr/local/bin/punic", line 11, in <module>
    load_entry_point('punic==0.2.5', 'console_scripts', 'punic')()
  File "/usr/local/lib/python2.7/site-packages/punic/punic_cli.py", line 369, in main
    punic_cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/punic/punic_cli.py", line 120, in resolve
    punic.resolve()
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 48, in resolve
    build_order = resolver.resolve_build_order()
  File "/usr/local/lib/python2.7/site-packages/punic/resolver.py", line 112, in resolve_build_order
    graph = self.resolve()
  File "/usr/local/lib/python2.7/site-packages/punic/resolver.py", line 40, in resolve
    for dependency, revisions in self._dependencies_for_node(self.root):
  File "/usr/local/lib/python2.7/site-packages/punic/resolver.py", line 141, in _dependencies_for_node
    return self.dependencies_for_node(node)
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 42, in _dependencies_for_node
    dependencies = self.dependencies_for_project_and_tag(identifier=node.identifier, tag=node.version)
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 172, in dependencies_for_project_and_tag
    return [make(specification) for specification in specifications]
  File "/usr/local/lib/python2.7/site-packages/punic/__init__.py", line 169, in make
    assert len(tags)
AssertionError: assertion len(tags) failed

**Comment by krbarnes** [comment]
There is something wrong in the resolver.py.

If you use `github "RxSwiftCommunity/RxRealm"` in it fails, but `github "danielgindi/Charts"` works. Both of these projects have `realm/realm-cocoa` in their Cartfiles, but RxRealm uses `~>2.1` and Charts uses `~2.1.1`

RxRealm Cartfile:
```
github "realm/realm-cocoa" ~> 2.1.1
```
Charts Cartfile:
```
github "realm/realm-cocoa" ~> 2.1
github "ReactiveX/RxSwift" ~> 3.1
```

**Comment by krbarnes** [comment]
The `prune_1` function of resolver.py is removing the correct version of realm-cocoa. Older versions in the graph had more than one predecessor and weren't removed, when it gets to the newest versions, it removes them all because they each only have 1 predecessor and `len(versions)` never gets to 1.

```
Testing realm/realm-cocoa
	versions [v1.0.0, v1.0.0-1, v1.0.0-2, v1.0.0-3, v1.0.1, v1.0.1-1, v1.0.1-2, v1.0.2, v1.0.2-1, v1.0.2-2, v1.0.2-3, v1.0.2-4, v1.0.2-5, v1.0.2-6, v1.0.2-7, v1.0.2-8, v1.0.2-9, v1.0.2-10, v1.0.2-11, v1.0.2-12, v1.0.2-13, v1.0.2-14, v1.0.2-15, v1.0.2-16, v1.0.2-17, v1.0.2-18, v2.0.0, v2.0.1, v2.0.2, v2.0.3, v2.0.4, v2.1.0, v2.1.1, v2.1.2]
		realm/realm-cocoa v1.0.0 predecessors: 10
		realm/realm-cocoa v1.0.0-1 predecessors: 10
		realm/realm-cocoa v1.0.0-2 predecessors: 10
		realm/realm-cocoa v1.0.0-3 predecessors: 10
		realm/realm-cocoa v1.0.1 predecessors: 10
		realm/realm-cocoa v1.0.1-1 predecessors: 10
		realm/realm-cocoa v1.0.1-2 predecessors: 10
		realm/realm-cocoa v1.0.2 predecessors: 10
		realm/realm-cocoa v1.0.2-1 predecessors: 10
		realm/realm-cocoa v1.0.2-2 predecessors: 10
		realm/realm-cocoa v1.0.2-3 predecessors: 10
		realm/realm-cocoa v1.0.2-4 predecessors: 10
		realm/realm-cocoa v1.0.2-5 predecessors: 10
		realm/realm-cocoa v1.0.2-6 predecessors: 10
		realm/realm-cocoa v1.0.2-7 predecessors: 10
		realm/realm-cocoa v1.0.2-8 predecessors: 10
		realm/realm-cocoa v1.0.2-9 predecessors: 10
		realm/realm-cocoa v1.0.2-10 predecessors: 10
		realm/realm-cocoa v1.0.2-11 predecessors: 10
		realm/realm-cocoa v1.0.2-12 predecessors: 10
		realm/realm-cocoa v1.0.2-13 predecessors: 10
		realm/realm-cocoa v1.0.2-14 predecessors: 10
		realm/realm-cocoa v1.0.2-15 predecessors: 10
		realm/realm-cocoa v1.0.2-16 predecessors: 10
		realm/realm-cocoa v1.0.2-17 predecessors: 10
		realm/realm-cocoa v1.0.2-18 predecessors: 10
		realm/realm-cocoa v2.0.0 predecessors: 4
		realm/realm-cocoa v2.0.1 predecessors: 4
		realm/realm-cocoa v2.0.2 predecessors: 4
		realm/realm-cocoa v2.0.3 predecessors: 4
		realm/realm-cocoa v2.0.4 predecessors: 4
		realm/realm-cocoa v2.1.0 predecessors: 1
			removing realm/realm-cocoa v2.1.0, Only one predecessor
		realm/realm-cocoa v2.1.1 predecessors: 1
			removing realm/realm-cocoa v2.1.1, Only one predecessor
		realm/realm-cocoa v2.1.2 predecessors: 1
			removing realm/realm-cocoa v2.1.2, Only one predecessor
```

my Cartfile was:
```
github "RxSwiftCommunity/RxRealm" 
```
and after running `punic resolve`, Cartfile.resolved was
```
github "ReactiveX/RxSwift" "3.1.0"
github "RxSwiftCommunity/RxRealm" "0.4.1"
```

There is a workaround that works for RxRealm. If you change to limit the set of potential matches (`github "RxSwiftCommunity/RxRealm" ~> 0.4.1`), the older versions with more than one predecessor  will be eliminated by the semantic versioning match and `punic resolve` will create the correct `Cartfile.resolved`

**Comment by nateboxer** [comment]
Thanks. That fixes this particular instance, but still seems like a worthwhile bug to fix.

**Comment by nateboxer** [comment]
Actually, this workaround doesn't work. It solves the problem inside the project that needs the dependency, but if that project is also a dependency of another project, the resolver fails.

I have a framework project with this in its Cartfile:

`github "RxSwiftCommunity/RxRealm" ~> 0.4.1`

In the framework's Cartfile.resolved:

`github "RxSwiftCommunity/RxRealm" "0.4.1"`
`github "realm/realm-cocoa" "v2.1.2"`

All good so far and RxRealm builds successfully. However, when I bring the framework into another project, the Cartfile.resolved is incorrect:

`github "RxSwiftCommunity/RxRealm" "0.4.1"`
`github "realm/realm-cocoa" "v1.0.2-18"`

And the build fails.

**Comment by schwa** [comment]
Looks like Realm has changed a lot recently. I'm going to figure out a way to make Realm & RxRealm more reliable and then make it so there's a repeating test build firing for those projects. Hopefully by end of today. Cheers for your patience.

**Comment by schwa** [comment]
As of punic 0.2.5 this all seems to work just fine:

```
schwa@ungoliant ~/D/p/RxRealm (master) [1]> cat Cartfile
github "RxSwiftCommunity/RxRealm"
schwa@ungoliant ~/D/p/RxRealm (master)> cat Cartfile.resolved 
github "ReactiveX/RxSwift" "3.1.0"
github "RxSwiftCommunity/RxRealm" "0.5.0"
github "realm/realm-cocoa" "v2.1.2"
schwa@ungoliant ~/D/p/RxRealm (master)> cat punic.yaml 
defaults:
  configuration: Debug
  platform: Mac
  xcode-version: 8.2.1
skips:
- [ macOS, realm-cocoa, CarthageExample.xcodeproj ]
- [ macOS, realm-cocoa, CocoaPodsDynamicExample.xcodeproj ]
- [ macOS, realm-cocoa, DynamicExample.xcodeproj ]
- [ macOS, realm-cocoa, CocoaPodsExample.xcodeproj ]
- [ macOS, realm-cocoa, RealmExamples.xcworkspace ]
- [ macOS, realm-cocoa, StaticExample.xcodeproj ]
schwa@ungoliant ~/D/p/RxRealm (master)> punic build
Build
Using xcode version: /Applications/Xcode.app (8.2.1)
Fetching: ReactiveX/RxSwift
Fetching: RxSwiftCommunity/RxRealm
Fetching: realm/realm-cocoa
Building: Rx.xcworkspace (scheme: RxBlocking-macOS, sdk: macosx, configuration: Debug)...
Building: Rx.xcworkspace (scheme: RxCocoa-macOS, sdk: macosx, configuration: Debug)...
Building: Rx.xcworkspace (scheme: RxSwift-macOS, sdk: macosx, configuration: Debug)...
Building: Rx.xcworkspace (scheme: RxTests-macOS, sdk: macosx, configuration: Debug)...
Building: Realm.xcworkspace (scheme: Realm, sdk: macosx, configuration: Debug)...
Building: Realm.xcworkspace (scheme: RealmSwift, sdk: macosx, configuration: Debug)...
Skipping: Mac / realm-cocoa / RealmExamples.xcworkspace / JSONImport
Skipping: Mac / realm-cocoa / RealmExamples.xcworkspace / DownloadCache
Skipping: Mac / realm-cocoa / RealmExamples.xcworkspace / PreloadedData
Building: RxRealm.xcodeproj (scheme: RxRealm-OSX, sdk: macosx, configuration: Debug)...
schwa@ungoliant ~/D/p/RxRealm (master)> 















```
